import mongoose from "mongoose";

const proactiveSendSchema = new mongoose.Schema({
  incidentType: { type: String, required: true, trim: true },
  location: { type: String, required: true, trim: true },
  clusterId: { type: String, default: null },
  documents: {
    hubNotice: { type: String, default: "" },
    customerEmail: { type: String, default: "" },
    faqUpdate: { type: String, default: "" },
    pccPlaybook: { type: String, default: "" },
  },
  status: { type: String, enum: ["draft", "sent"], default: "draft" },
  sentDocuments: [{ type: String }],
  sentAt: { type: Date, default: null },
  sentBy: { type: String, default: null },
  estimatedComplaintsPrevented: { type: Number, default: 0 },
  customerEmailsContacted: [{ type: String, default: [] }],
  generatedAt: { type: Date, default: Date.now },
  autoGenerated: { type: Boolean, default: false },
  acknowledgedAt: { type: Date, default: null },
  acknowledgedBy: { type: String, default: null },
  acknowledgedNote: { type: String, default: null },
});

proactiveSendSchema.index({ generatedAt: -1 });
proactiveSendSchema.index({ sentAt: -1 });

const ProactiveSend =
  mongoose.models.ProactiveSend ||
  mongoose.model("ProactiveSend", proactiveSendSchema);

export default ProactiveSend;
